// src/js/pages/Home.tsx
import EmailAggregationForm from 'components/EmailAggregationForm';
import React from 'react';
import logo from 'resources/images/logo-banner-768.png';
import styled from 'styled-components';

const HomeContainer = styled.div`
	display: flex;
	flex-direction: column;
	padding: 16px;
`;

const LogoBanner = styled.img`
	margin: 24px auto;
	width: 90%;

	@media (min-width: 425px) {
		width: 70%;
	}

	@media (min-width: 768px) {
		width: 60%;
	}
`;

const Home = () => {
	return (
		<HomeContainer>
			<LogoBanner alt="Your Story Project Logo" src={logo} />
			<EmailAggregationForm />
		</HomeContainer>
	);
};

export default Home;

// src/views/Home.vue
<template>
  <div class="home">
    <img class="logo" alt="Your Story Project logo" src="../assets/logo.png" />
    <TheHomePageHeader />
  </div>
</template>

<script>
// @ is an alias to /src
import TheHomePageHeader from '@/components/TheHomePageHeader';
export default {
  name: 'Home',
  components: { TheHomePageHeader },
};
</script>

<style lang="scss" scoped>
.logo {
  height: 100px;
}
</style>
